### ISSUE TITLE
ReactNative.createClass is deprecated RN v0.25.x 

### ISSUE THREAD

**Issue by jcsena** [iodine/react-native-drawer-layout#66]
ReactNative.createClass is deprecated. Use React.createClass from the "react" package instead.

**Comment by DanielMSchmidt** [comment]
Hey, thanks for letting us know! 

If I see this correctly, we would have to
- [x] bump up the `react-native` dependency 
- [x] add a `react` dependency
- [x] Use `React.createClass` instead of `ReactNative.createClass`
- [x] Add a note in the readme, that states the last version number for RN < 0.25
- [x] release a new major version, as there are breaking changes

As I am currently on vacation, I can not solve this problem right now. Would you or anyone else interested in seeing this done mind doing a PR? 

Have a nice day!

**Comment by DanielMSchmidt** [comment]
Hey,

Thanks for your PR, I added a small part on the documentation and published a new major version as these are breaking changes.

If you would like to use this library with React Native 0.25 version 1.x.x should be your choice.

Have a nice day!
